# Generated by Django 4.1 on 2022-08-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_report_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(default='alexquiranza@gmail.com', max_length=254),
        ),
    ]
