# Generated by Django 4.1 on 2022-08-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_report_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
